# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

run-name: Node.js CI ${{ github.event_name == 'push' && contains(github.event.ref, 'master') && 'production' || 'staging' }}
name: Node.js Deployment Pipeline

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: self-hosted
    environment:
      name: ${{ github.event_name == 'push' && contains(github.event.ref, 'master') && 'production' || 'stagging' }}

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: git checkout ${{ github.event.ref }}
      - run: git pull origin ${{ github.event.ref }}

      - name: "Create env file"
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - run: yarn install --frozen-lockfile
      - run: pm2 restart ${{ github.event_name == 'push' && contains(github.event.ref, 'master') && 'production' || 'staging' }}-server
